### PR TITLE
Use arduino-executable in commands instead

### PR DESCRIPTION
**Pull request by concavegit**
Before, setting arduino-executable did not do much because the commands used "arduino" no matter what. Also, I notice that the melpa package is tied to a specific commit. In the case that this request is merged, could you update the package to this commit or set the melpa package to master?

### CODE REVIEW

**Comment by concavegit** [comment]
@stardiviner Good to merge?

**Comment by stardiviner** [comment]
Sorry I saw this late. I'm sure GitHub has delay on this notification. My Emacs daemon fetch GitHub notifications regularly, but it get updated until now.
About point MELPA package to master, what do you mean?

**Comment by stardiviner** [comment]
I checked MELPA recipe `arduino-mode` have not specify branch in recipe, and GitHub page of my `arduino-mode` page, default branch is `master`.

**Comment by stardiviner** [comment]
I just remember that MELPA recipe seems has an option `:branch "master"`. Did you mean this? I'm not sure what it does.

**Pull request merged**
